force-app/main/default/objects/BusRoute__c/BusRoute__c.object-meta.xml
<CustomObject>
    <description>Bus Route</description>
    <label>Bus Route</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bus Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BusRoute__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>End Time of the Route</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/BusRoute__c/fields/RouteNumber__c.field-meta.xml
<CustomField>
    <fullName>RouteNumber__c</fullName>
    <label>Route Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusRoute__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Start Time of the Route</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/BusStop__c/BusStop__c.object-meta.xml
<CustomObject>
    <description>Bus stop. May be a lot of stops in the route.</description>
    <label>Bus Stop</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>Time for every route on every stop.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/BusRoute__c.field-meta.xml
<CustomField>
    <fullName>BusRoute__c</fullName>
    <label>Bus Route</label>
    <referenceTo>BusRoute__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/BusStop__c.field-meta.xml
<CustomField>
    <fullName>BusStop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bus Stop</label>
    <referenceTo>BusStop__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/TimeToNextStop__c.field-meta.xml
<CustomField>
    <fullName>TimeToNextStop__c</fullName>
    <description>Time in minutes to the next stop in a route.</description>
    <label>Time To Next Stop</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ScheduleTriggerTest.cls
@isTest
private class ScheduleTriggerTest {
    @testSetup
    static void dataSetup() {
        BusRoute__c newBusRoute = new BusRoute__c(
            RouteNumber__c = '111D',
            StartTime__c = Time.newInstance(0, 0, 0, 0),
            EndTime__c = Time.newInstance(0, 0, 0, 0)
        );
        insert newBusRoute;
        
        TransportServices.createStop('Stop6', 'Address6');
        TransportServices.createStop('Stop7', 'Address7');
        TransportServices.createStop('Stop8', 'Address8');
        
        Integer i = 1;
        for(BusStop__c busStop: [SELECT Id FROM BusStop__c]) {
            TransportServices.addStopToSchedule(newBusRoute.Id, busStop.Id, Time.newInstance(i, 0, 0, 0));
            i += 1;
        }
    }
    
    @isTest
    static void onAfterInsertUpdateStartEndTimeTest() {
        Test.startTest();        
        List<BusRoute__c> busRoute = [SELECT StartTime__c, EndTime__c FROM BusRoute__c];
        Test.stopTest();
        
        System.assert(busRoute[0].StartTime__c == Time.newInstance(1, 0, 0, 0) && busRoute[0].EndTime__c == Time.newInstance(3, 0, 0, 0), 'Wrong start time: '+String.valueOf(busRoute[0].StartTime__c));
    }
    
    @isTest
    static void onAfterInsertUpdateTimeToNextStopTest() {
        Test.startTest();        
        List<Schedule__c> schedules = [SELECT TimeToNextStop__c FROM Schedule__c];
        Test.stopTest();
        
        System.assert(schedules[0].TimeToNextStop__c == 60, 'Wrong start time: '+String.valueOf(schedules[0].TimeToNextStop__c));
    }
}