force-app/main/default/objects/BusRoute__c/BusRoute__c.object-meta.xml
<CustomObject>
    <description>Bus Route</description>
    <label>Bus Route</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bus Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BusRoute__c/fields/DurationInMinutes__c.field-meta.xml
<CustomField>
    <fullName>DurationInMinutes__c</fullName>
    <formula>(UNIXTIMESTAMP(EndTime__c)  - UNIXTIMESTAMP(StartTime__c))/60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration In Minutes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BusRoute__c/fields/RouteNumber__c.field-meta.xml
<CustomField>
    <fullName>RouteNumber__c</fullName>
    <label>Route Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusStop__c/BusStop__c.object-meta.xml
<CustomObject>
    <description>Bus stop. May be a lot of stops in the route.</description>
    <label>Bus Stop</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>Time for every route on every stop.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/BusRoute__c.field-meta.xml
<CustomField>
    <fullName>BusRoute__c</fullName>
    <label>Bus Route</label>
    <referenceTo>BusRoute__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/BusStop__c.field-meta.xml
<CustomField>
    <fullName>BusStop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bus Stop</label>
    <referenceTo>BusStop__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/TimeToNextStop__c.field-meta.xml
<CustomField>
    <fullName>TimeToNextStop__c</fullName>
    <description>Time in minutes to the next stop in a route.</description>
    <label>Time To Next Stop</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TransportDAO.cls
public class TransportDAO {
    public Integer getNumberOfStops(Id busRouteId) {
        return (Integer) [SELECT COUNT(BusStop__c)BusStop, BusRoute__c
        FROM Schedule__c 
        WHERE BusRoute__c = :busRouteId 
        GROUP BY BusRoute__c][0].get('BusStop');
    }

    public Id getLongestByTimeRouteId() {
        return [SELECT Id FROM BusRoute__C ORDER BY DurationInMinutes__c DESC LIMIT 1].Id;
    }
    
    public List<Schedule__c> getSchedules(Integer lim, Integer offset) {
        return [SELECT Name, BusRoute__c, BusStop__c, Time__c, TimeToNextStop__c 
        FROM Schedule__c LIMIT :lim OFFSET :offset];
    }
    
    public List<BusStop__c>  getBusStopsByIds(Set<Id> busStops) {
        return [SELECT Name, Address__c FROM BusStop__c WHERE Id IN :busStops];
    }
    
    public List<BusRoute__c> getBusRoutes(Set<Id> bustStops) {
        return [SELECT Name, RouteNumber__c FROM BusRoute__c WHERE Id IN (SELECT BusRoute__c FROM Schedule__c WHERE BusStop__c IN :bustStops)];
    }

    public Map<Id, String> getBusRoutesWithMinDuration(Integer lim) {
        Map<Id, String> routes = new Map<Id, String>();

        for(BusRoute__c route: [SELECT RouteNumber__c FROM BusRoute__c ORDER BY DurationInMinutes__c ASC LIMIT :lim]) {
            routes.put(route.Id, route.RouteNumber__c);
        }

        return routes;
    }

    public Map<Id, String> getBusRoutesWithMaxDuration(Integer lim) {
        Map<Id, String> routes = new Map<Id, String>();

        for(BusRoute__c route: [SELECT RouteNumber__c FROM BusRoute__c ORDER BY DurationInMinutes__c DESC LIMIT :lim]) {
            routes.put(route.Id, route.RouteNumber__c);
        }

        return routes;
    }
}


// TransportDAO transportObj = new TransportDAO();
// Set<Id> bustStops = new Set<Id>();
// bustStops.add('a017Q000018uwBqQAI');
// bustStops.add('a017Q000018uwC1QAI');

// System.debug(transportObj.getNumberOfStops('a007Q00000AtvQnQAJ'));
// System.debug(transportObj.getLongestByTimeRouteId());
// System.debug(transportObj.getSchedules(1, 2));
// System.debug(transportObj.getBusStopsByIds(bustStops));
// System.debug(transportObj.getBusRoutes(bustStops));
// System.debug(transportObj.getBusRoutesWithMinDuration(3));
// System.debug(transportObj.getBusRoutesWithMaxDuration(3));