force-app/main/default/objects/BusRoute__c/BusRoute__c.object-meta.xml
<CustomObject>
    <description>Bus Route</description>
    <label>Bus Route</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bus Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BusRoute__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>End Time of the Route</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/BusRoute__c/fields/RouteNumber__c.field-meta.xml
<CustomField>
    <fullName>RouteNumber__c</fullName>
    <label>Route Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusRoute__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Start Time of the Route</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/BusStop__c/BusStop__c.object-meta.xml
<CustomObject>
    <description>Bus stop. May be a lot of stops in the route.</description>
    <label>Bus Stop</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>Time for every route on every stop.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/BusRoute__c.field-meta.xml
<CustomField>
    <fullName>BusRoute__c</fullName>
    <label>Bus Route</label>
    <referenceTo>BusRoute__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/BusStop__c.field-meta.xml
<CustomField>
    <fullName>BusStop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bus Stop</label>
    <referenceTo>BusStop__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TransportServicesTest.cls
@isTest
public class TransportServicesTest {
    @testSetup
    static void dataSetup() {
        BusRoute__c newBusRoute = new BusRoute__c(
            RouteNumber__c = '111D',
            StartTime__c = Time.newInstance(0, 0, 0, 0),
            EndTime__c = Time.newInstance(0, 0, 0, 0)
        );
        insert newBusRoute;
        
        TransportServices.createStop('Stop6', 'Address6');
        TransportServices.createStop('Stop7', 'Address7');
        TransportServices.createStop('Stop8', 'Address8');
        
        Integer i = 1;
        for(BusStop__c busStop: [SELECT Id FROM BusStop__c]) {
            TransportServices.addStopToSchedule(newBusRoute.Id, busStop.Id, Time.newInstance(i, 0, 0, 0));
            i += 1;
        }
    }
    
    @isTest
    static void createStopTest() {
        Test.startTest();        
        List<BusStop__c> busStops = [SELECT Id FROM BusStop__c];
        Test.stopTest();
        
        System.assert(busStops.size() == 3, 'Wrong size of stops list: '+String.valueOf(busStops.size()));
    }
    
    @isTest
    static void addStopToScheduleTest() {
        Test.startTest();        
        List<Schedule__c> schedules = [SELECT Id FROM Schedule__c];
        Test.stopTest();
        
        System.assert(schedules.size() == 3, 'Wrong size of schedules list: '+String.valueOf(schedules.size()));
    }
    
    @isTest
    static void updateScheduleTimesTest() {
        Test.startTest();  
        Integer i = 1;
        List<Schedule__c> schedules = [SELECT Id, Time__c  FROM Schedule__c];
        for(Schedule__c schedule: schedules) {
            schedule.Time__c = Time.newInstance(i, i, 0, 0);  
            i += 1;
        }
        TransportServices.updateScheduleTimes(schedules);
      	schedules = [SELECT Id, Time__c  FROM Schedule__c];
        Test.stopTest();
        
        System.assert(schedules[0].Time__c == Time.newInstance(1, 1, 0, 0), 'Wrong size of schedules list: '+String.valueOf(schedules[0].Time__c));
    }
    
    @isTest
    static void deleteBusStopTest() {
        Test.startTest(); 
        for(BusStop__c busStop: [SELECT Id FROM BusStop__c]) {
            TransportServices.deleteBusStop(busStop.Id);
        }
        List<BusStop__c> busStops = [SELECT Id FROM BusStop__c];
        Test.stopTest();
        
        System.assert(busStops.size() == 0, 'Wrong size of stops list: '+String.valueOf(busStops.size()));
    }
}