force-app/main/default/objects/BusRoute__c/BusRoute__c.object-meta.xml
<CustomObject>
    <description>Bus Route</description>
    <label>Bus Route</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bus Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BusRoute__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>End Time of the Route</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/BusRoute__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Start Time of the Route</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>Time for every route on every stop.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/BusRoute__c.field-meta.xml
<CustomField>
    <fullName>BusRoute__c</fullName>
    <label>Bus Route</label>
    <referenceTo>BusRoute__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/TimeToNextStop__c.field-meta.xml
<CustomField>
    <fullName>TimeToNextStop__c</fullName>
    <description>Time in minutes to the next stop in a route.</description>
    <label>Time To Next Stop</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ScheduleTriggerHandler.cls
public class ScheduleTriggerHandler {
    public static void onAfterInsert(List<Schedule__c> schedules) {
        Set<Id> busRouteIds = new Set<Id>();
        for(Schedule__c schedule: schedules) {
            busRouteIds.add(schedule.BusRoute__c);
        }
        
        List<Schedule__c> allTimeOfRoute = [SELECT Id, BusRoute__c, Time__c FROM Schedule__c WHERE BusRoute__c IN :busRouteIds ORDER BY BusRoute__c, Time__c ASC];
        List<SObject> objectsToUpdate = new List<SObject>();
        List<Schedule__c> sliceAllTimeOfROute = new List<Schedule__c>();
        
        for(Schedule__c timeRoute: allTimeOfRoute) {
            sliceAllTimeOfROute.add(timeRoute);
            
            if((allTimeOfRoute.indexOf(timeRoute)==allTimeOfRoute.size()-1) || (allTimeOfRoute.indexOf(timeRoute)+1 < allTimeOfRoute.size() && timeRoute.BusRoute__c != allTimeOfRoute[allTimeOfRoute.indexOf(timeRoute)+1].BusRoute__c)) {
                objectsToUpdate.add(new BusRoute__c(
                    Id = sliceAllTimeOfROute[0].BusRoute__c,
                    StartTime__c = sliceAllTimeOfROute[0].Time__c,
                    EndTime__c = sliceAllTimeOfROute[sliceAllTimeOfROute.size()-1].Time__c
                ));
                
                if(allTimeOfRoute.size() > 1){
                    Integer TimeToNextStop = schedules[0].Time__c.hour()*60 + schedules[0].Time__c.minute() -  sliceAllTimeOfROute[sliceAllTimeOfROute.size()-2].Time__c.hour()*60 -  sliceAllTimeOfROute[sliceAllTimeOfROute.size()-2].Time__c.minute();
                    objectsToUpdate.add(new Schedule__c (
                        Id = sliceAllTimeOfRoute[sliceAllTimeOfRoute.size()-2].Id,
                        TimeToNextStop__c = TimeToNextStop
                    ));
                }
                
                sliceAllTimeOfROute.clear();
            }
        }
        
        try { 
            update objectsToUpdate;
        } catch (DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
        }
    }
    
    
    public static void onAfterUpdate(List<Schedule__c> schedules) {
        Set<Id> busRouteIds = new Set<Id>();
        for(Schedule__c schedule: schedules) {
            busRouteIds.add(schedule.BusRoute__c);
        }
        
        List<Schedule__c> allTimeOfRoute = [SELECT Id, BusRoute__c, Time__c FROM Schedule__c WHERE BusRoute__c IN :busRouteIds ORDER BY BusRoute__c, Time__c ASC];
        List<SObject> objectsToUpdate = new List<SObject>();
        List<Schedule__c> sliceAllTimeOfROute = new List<Schedule__c>();
        
        for(Schedule__c timeRoute: allTimeOfRoute) {
            if (allTimeOfRoute.indexOf(timeRoute) == 0) {
                Schedule__c NextScheduleItem = allTimeOfRoute[allTimeOfRoute.indexOf(timeRoute)+1];
                timeRoute.TimeToNextStop__c = NextScheduleItem.Time__c.hour()*60 + NextScheduleItem.Time__c.minute() -  timeRoute.Time__c.hour()*60 -  timeRoute.Time__c.minute();
            } else if (allTimeOfRoute.indexOf(timeRoute) == allTimeOfRoute.size()-1) {
                timeRoute.TimeToNextStop__c = 0;
            } else {
                Schedule__c NextScheduleItem = allTimeOfRoute[allTimeOfRoute.indexOf(timeRoute)+1];
                Schedule__c PrevScheduleItem = allTimeOfRoute[allTimeOfRoute.indexOf(timeRoute)+1];
                PrevScheduleItem.TimeToNextStop__c = timeRoute.Time__c.hour()*60 + timeRoute.Time__c.minute() -  PrevScheduleItem.Time__c.hour()*60 -  PrevScheduleItem.Time__c.minute();
                timeRoute.TimeToNextStop__c = NextScheduleItem.Time__c.hour()*60 + NextScheduleItem.Time__c.minute() -  timeRoute.Time__c.hour()*60 -  timeRoute.Time__c.minute();
            }
        }
        
        for(Schedule__c timeRoute: allTimeOfRoute) { 
            sliceAllTimeOfROute.add(timeRoute);
            
            if((allTimeOfRoute.indexOf(timeRoute)==allTimeOfRoute.size()-1) || (allTimeOfRoute.indexOf(timeRoute)+1 < allTimeOfRoute.size() && timeRoute.BusRoute__c != allTimeOfRoute[allTimeOfRoute.indexOf(timeRoute)+1].BusRoute__c)) {
                objectsToUpdate.add(new BusRoute__c(
                    Id = sliceAllTimeOfROute[0].BusRoute__c,
                    StartTime__c = sliceAllTimeOfROute[0].Time__c,
                    EndTime__c = sliceAllTimeOfROute[sliceAllTimeOfROute.size()-1].Time__c
                ));
                
                sliceAllTimeOfROute.clear();
            }
        }
        
        try { 
            update allTimeOfRoute;
            update objectsToUpdate;
        } catch (DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
        }
    }
}